# Generated by Django 2.1.2 on 2020-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.CharField(choices=[('minimal', 'Сидячий режим весь день'), ('low', 'Минимальная активность'), ('mid', 'Средняя активность'), ('high', 'Тяжелая работа и/или нагрузка'), ('very_high', 'Экстрим')], max_length=50, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target',
            field=models.CharField(choices=[('gain', 'Эктоморф, энергичный, худой, быстрый'), ('losing', 'Эндоморф, полный, широкий и медлительный'), ('maintenance', 'Мезоморф, достаточно мускулистый, средний')], max_length=50, verbose_name='Телосложение'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Subject',
            field=models.CharField(choices=[('recept', 'Полезные рецепты'), ('bars', 'Десерты'), ('cocktails', 'Коктейли'), ('lifestyle', 'Здоровое питание')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='training',
            name='subject',
            field=models.CharField(choices=[('body', ''), ('legs', ''), ('press', ''), ('cardio', '')], max_length=50, verbose_name='Тип'),
        ),
    ]
