# Generated by Django 2.1.2 on 2020-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0002_auto_20200826_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target',
            field=models.CharField(choices=[('trening', 'Эктоморф, энергичный, худой, быстрый'), ('losing', 'Эндоморф, полный, широкий и медлительный'), ('maintenance', 'Мезоморф, достаточно мускулистый, средний')], max_length=50, verbose_name='Телосложение'),
        ),
    ]
