# Generated by Django 2.1.2 on 2020-08-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0003_auto_20200826_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.PositiveIntegerField(default=0, verbose_name='Шаги в день'),
        ),
    ]
