# Generated by Django 2.1.2 on 2020-08-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0004_profile_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipes',
        ),
        migrations.DeleteModel(
            name='training',
        ),
    ]
